### ISSUE TITLE
/bin/fex: line 14: syntax error: unexpected "("

### ISSUE THREAD

**Issue by vsystech** [radroxx/fex.net#2]
Hello, i'm install this app, but when type fex or any command get the following error: 

/bin/fex: line 14: syntax error: unexpected "("

**Comment by radroxx** [comment]
What is your linux distributions?
What version busybox are you using?

**Comment by MakselPr** [comment]
Та же проблема
root@n1:/bin# fex
/bin/fex: line 14: syntax error: unexpected "("
root@n1:/bin# cat /etc/debian_version
9.7
BusyBox v1.22.1 (Debian 1:1.22.0-19+b3) multi-call binary.
root@n1:/bin# ash
#

**Comment by radroxx** [comment]
I am rewritten 80% code, so fixed this problem, but this is not exactly.

**Comment by vsystech** [comment]
Dear radroxx, thanks your reply. i'm test again the new version but not working :( 

root@cdn2 ~ # fex
/bin/fex: 15: /bin/fex: Syntax error: "(" unexpected
