### ISSUE TITLE
/bin/fex: 15: /bin/fex: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by vsystech** [radroxx/fex.net#3]
Hello, thanks to update the script but not working for me. 

root@cdn2 ~ # fex
/bin/fex: 15: /bin/fex: Syntax error: "(" unexpected

Can you send your skype or email or discord id maybe ?

**Comment by radroxx** [comment]
Please change first string from `#!/bin/sh` to `#!/bin/bash` and check work. If don't work, my telegram @radroxx.

**Comment by radroxx** [comment]
The author has not responded for long.

**Comment by radroxx** [comment]
If you use debian and bash, please change firs string to 
```sh
#!/bin/bash

shopt -s expand_aliases
```
