### ISSUE TITLE
не получается загрузить файл на fex

### ISSUE THREAD

**Issue by 223532735** [radroxx/fex.net#5]
При попытке загрузить
fex file anonymous add /Users/admin/Downloads/the-tree-LRNDRSJ.jpg

выводится такая ошибка 
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

Или я не правильно указываю команду?

операционка - mac os 10.12.6

**Comment by radroxx** [comment]
там нужно сначала токен получить посмотри как в файле fex-backup

**Comment by 223532735** [comment]
Спасибо с загрузкой разобрался ))) правда если в именах есть пробелы то все что после пробела отрезается и выдается ошибка:

**wc: /Users/admin/proba/Acoustic: open: No such file or directory
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information**

Теперь не могу разобраться как скачать не один, а все файлы которые есть по ссылке?
Как пример я делаю так:

**fex file ATOKEN get https://fex.net/s/kvfmdmz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
     Dload  Upload   Total   Spent    Left  Speed
 100    26  100    26    0     0     16      0  0:00:01  0:00:01 --:--:--    16
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information**

Что я делаю не так?

**Comment by radroxx** [comment]
Попробуй оборачивать имена в кавычки должно помочь с пробелами, если не поможет пиши гляну, так не должно быть.
fex file ${TOKEN} add "/user/home/tets/my super file.txt"  - как то так

Качать все вместе нельзя, можно из интерфейса скачать все в одном zip, или через xargs типа такого.
fex file ${TOKEN} list | awk '{print $1}' | xargs -n1 -t -I {} fex file ${TOKEN} get "{}" - писал как пример нужно смотреть что именно нужно оставить из вывода list и я не помню создаю там дерево директорий или просто файл выгружаю. Вообщем могут быть нюансы.

**Comment by 223532735** [comment]
Попробовал обернуть имя файла в кавычки по моему не помогло и пробелы все равно обрезаются и загрузка не происходит:
**.sh /Users/admin/Acoustic\ Rock.mp3
https://fex.net/s/vovy6tt
wc: /Users/admin/Acoustic\: open: No such file or directory
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information**


Не выходит скачать файл с fex.net .
подставляю ключ из ссылки и получаю список объектов 
**fex file ATOKEN list share/ключ**
из полученного списка беру ID файла и NAME файла - ввожу в сторку  
**fex file ATOKEN get ID файла NAME файла** 
но ничего не скачивается в ответ получаю:

`% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                        Dload  Upload   Total   Spent    Left  Speed
100    27  100    27    0     0    180      0 --:--:-- --:--:-- --:--:--   181
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information`

Так же заметил что при получении списка объектов fex file ATOKEN list
Имя файла в находится поле NAME а если есть директория то ее имя в поле CRC32
