### ISSUE TITLE
Підкажіть, як користуватися

### ISSUE THREAD

**Issue by hidden2010** [radroxx/fex.net#8]
Добрый день.
Мне надо настроить бекап файлов сервера Windows на зарегистрированный аккаунт Fex.net
Не совсем понял как пользоваться инструментом. Исходный код вижу, а где сама утилита? Есть возможность получить exe файл под винду? Можете подсказать где взять описание API для FEX. Я бы тогда сам смог написать обмен с сервисом.
Спасибо

**Comment by radroxx** [comment]
Добрый день, к сожалению fex.net не публикует api, я писал первую версию скрипта разбирая api в браузере, оно оказалось достаточно простым. Они ввели скрытую каптчу и это поломало логин, я в рамках данного проекта не считаю целесообразным заниматься обходом каптчи. Если fex когда-то опубликует api или хотя бы возможность логиниться по токену и позволит нормально с ним работать, скорей всего, я вернусь к данному проекту. У меня сейчас нет не времени не желания заниматься обходом каптчи, а без логина и привлекательного тарифа, fex.net не имеет не одного преимущества перед другими облачными хранилищами.
